blank_issues_enabled: false
contact_links:
  - name: General question
    url: https://github.com/SLINIcraftet204/UsefulAllays/discussions
    about: Use discussions for ideas, balancing and general questions.
